__title__ = 'eeweather'
__description__ = 'Weather for Open Energy Efficiency Meter'
__url__ = 'http://github.com/openeemeter/eeweather'
__version__ = '0.3.7'
__author__ = 'Phil Ngo'
__author_email__ = 'phil@openee.io'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2018 Open Energy Efficiency, Inc.'
